# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf511324da25a2fca15226276ee491e0da4573dd3758fa3aa50ad6762e2bc81b3ec6aa6b7e235c6d3bff93aee77dd6808980e68b838f289b37c1e24250753b3b

test:
  secret_key_base: b979437b6a3ef038797203b114b6e3163bab8d5c5e4f480176e21c5656e63fb402e37cc0c451987520da974dc4ee55b7789e07d3f28cd9e075e69daa34f34013

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
